---
##Verify if monit is installed
- name: verify monitrc presence
  stat:
    path=/etc/monitrc
  register: monit_conf

##Install monit if not present
# - include: install.yml
#   when: not monit_conf.stat.exists

- name: Install monit
  yum: name=monit state=latest

- name: Monit Configuration file
  template:
    src: monitrc.j2
    dest: /etc/monitrc
    owner: root
    group: root
    mode: "0700"
  notify:
      - start monit
