---

##########SSH Welcome Banner##########
- name: ssh welcome banner
  copy: src=awgsshbanner.txt dest=/etc/awgsshbanner.txt owner=root group=root mode=644

- name: AWG SSH Banner
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^Banner'
    line: 'Banner /etc/awgsshbanner.txt'
  notify:
    - restart sshd
##########MOTD Configutation##########
- name: Install Firemotd
  command: make install
  args:
    chdir: /samnt/scripts/FireMotD-5.14.160701
    creates: /usr/local/bin/FireMotD
  register: makeinstall

- name: make_bash
  when: makeinstall|changed
  command: make bash_completion
  args:
    chdir: /samnt/scripts/FireMotD-5.14.160701

- name: Root Bash Profile MOTD
  lineinfile:
    dest: /root/.bash_profile
    state: present
    regexp: '^/usr/local/bin/FireMotD'
    line: '/usr/local/bin/FireMotD -t blue ###MOTD Server Infor/Performance in Blue Color'

##########Crontab task is in a seperate .yml file, so we need to include it to this main.yml file##########
- include: crontab.yml


