---
###Role:Configuration Standards
###Owned by: Server Team, AWG
###Maintained by Roderick Rabelo (roderick.rabelo@awginc.com)
##
#
####Adds Rundeck public key to root Authorized Keys####
- name: Add Rundeck key to root authorized_keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - rundeck_key
