---
###Role: Packages Standards. RPM packages that are required on every server
###Owned by: Server Team, AWG
###Maintained by Roderick Rabelo (roderick.rabelo@awginc.com)
##
#
####INSTALLATION OF STANDARD PACKAGES####
- name: Install Standard packages
  yum: state=present name={{ item }}
  with_items:
    - nfs-utils
    - setroubleshoot-server
    - vim
    - ntp
    #- logwatch # No longer needed. We have graylog
    - tzdata
    - cifs-utils
    - katello-agent
    - htop
    - nmon
    - cockpit

#- name: Start and Enable Cockpit
#  service: name=cockpit.socket state=started enabled=yes
