---
# tasks file for jffz.netdata
- name: update the apt cache
  apt: >
        update_cache=yes
        cache_valid_time=86400
  when: ansible_os_family == "Debian"
  
- name: "Install pre-requisites"    
  apt:
    name: "{{ item }}"
    state: present
  with_items: 
    "{{ debian.packages }}"
  when: ansible_os_family == "Debian"
  
- name: "EPEL repo"
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: "Install pre-requisites"    
  yum:
    name: "{{ item }}"
    state: present
  with_items: 
    "{{ rhel.packages }}"
  when: ansible_os_family == "RedHat"

#Clone reopo into source and keep it for later (upgrade)
- name: "Clone repo"
  git:
    clone: yes
    update: yes
    repo: https://github.com/firehol/netdata.git
    dest: /usr/src/netdata
  register: gitupdate

- name: "Installation"
  shell: cd /usr/src/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here
  notify:  Restart netdata
  when: gitupdate.changed


# we keep the sources for upgrades
#- name: "Clean git repo"
#  file:
#    path: /usr/src/netdata
#    state: absent


#Optional: use your own registry
- lineinfile:
    dest: /etc/netdata/netdata.conf
    regexp: '^\t# registry to announce.*'
    line: '\t registry to announce = http://{{ ansible_hostname }}:19999'
    backrefs: yes

#Optional: Disable notifications
#- lineinfile:
#    dest: /etc/netdata/health_alarm_notify.conf
#    regexp: '^SEND_EMAIL="YES"'
#    line: 'SEND_EMAIL="NO"'
#    backrefs: yes


#ToDo Uninstaller -  see netdata-uninstaller.sh
