---
#Install Pre-requisites
- name: "Install pre-requisites"
  shell: curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all --dont-wait --non-interactive

#Clone reopo into source and keep it for later (upgrade)
- name: "Clone repo"
  git:
    clone: yes
    update: yes
    repo: https://github.com/firehol/netdata.git
    dest: /usr/src/netdata
  register: gitupdate

- name: "Installation"
  shell: cd /usr/src/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here
# notify:  Restart netdata
  when: gitupdate.changed

- name: Netdata AWG Configurations
  template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
  notify:
      - Restart netdata

# we keep the sources for upgrades
#- name: "Clean git repo"
#  file:
#    path: /usr/src/netdata
#    state: absent

#Optional: use your own registry
- lineinfile:
    dest: /etc/netdata/netdata.conf
    regexp: '^\t# registry to announce.*'
    line: '\t registry to announce = http://{{ ansible_hostname }}:19999'
    backrefs: yes


#Optional: Disable notifications
#- lineinfile:
#    dest: /etc/netdata/health_alarm_notify.conf
#    regexp: '^SEND_EMAIL="YES"'
#    line: 'SEND_EMAIL="NO"'
#    backrefs: yes


#ToDo Uninstaller -  see netdata-uninstaller.sh
