---
# defaults file for lynis

lynis_version: 2.5.2
lynis_version_sha256sum: 6b4dc74ec0faa009fc5d34f8ab85895e53c6f4f02bc160377905dcb95b0585a1

lynis_src_directory: /usr/local/src

lynis_dest_directory: /opt

lynis_log_directory: /var/log/lynis

lynis_cron: yes
lynis_cron_hour: 3
lynis_cron_minute: 30
