---

- name: manage plugins OS agnostic
  action: >
    {{ ansible_pkg_mgr }}
    name="{{ foreman_plugin_prefix }}{{ item }}"
    state={{ foreman_plugins_state }}
  with_items: foreman_plugins
  tags:
    - foreman-plugins-install
    - foreman-plugins-debug

- include: plugins/discovery.yml
  when: "'discovery' in {{ foreman_plugins|list }}"
