---
## Install Required packages
- name: Install AD required packages
  yum: state=present name={{ item }}
  with_items:
    - oddjob
    - oddjob-mkhomedir
    - adcli
    - sssd
    - realmd

  ## Create realmd file
- name: Create Realmd Config file
  blockinfile:
    path: /etc/realmd.conf
    block: |
      [users]
      default-home = /home/%d/%u
    create: yes

## Tasks to Join servers to AWG Domain
- name: Preset Computer Object
  shell: echo -n '4rfvVFR$' |adcli preset-computer --stdin-password --domain=awg.local --domain-ou="ou=LINUX,ou=UNIX,ou=Internal Servers,dc=AWG,dc=Local" --login-user=Service_RHEL {{ ansible_hostname }}
  ignore_errors: true

- name: Wait for Domain Controllers to Sync....
  pause: seconds=20

- name: Reset Computer Object
  shell: echo -n '4rfvVFR$' |adcli reset-computer --stdin-password --domain=awg.local --login-user=Service_RHEL {{ ansible_hostname }}

- name: Wait for Domain Controllers to Sync....
  pause: seconds=60

- name: Join the AWG Realm
  shell: realm join awg.local --one-time-password={{ ansible_hostname }} --computer-ou="ou=LINUX,ou=UNIX,ou=Internal Servers,dc=AWG,dc=Local"

## Disable FQDN for User Authentication
- name: Disable sssd need for FQDN
  lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: '^use_fully_qualified_names ='
    line: 'use_fully_qualified_names = False'
