---
####Install Pre-requisites####
- name: "Install pre-requisites"
  shell: curl -Ss 'https://raw.githubusercontent.com/firehol/netdata-demo-site/master/install-required-packages.sh' >/tmp/kickstart.sh && bash /tmp/kickstart.sh -i netdata-all --dont-wait --non-interactive
- debug: var=pre.stdout_lines

####Clone reopo into source and keep it for later (upgrade)####
- name: "Clone repo"
  git:
    clone: yes
    update: yes
    repo: https://github.com/firehol/netdata.git
    dest: /usr/src/netdata
  register: gitupdate

#### Installation of netdata using their script####
- name: "Installation"
  shell: cd /usr/src/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here
  when: gitupdate.changed
- debug: var=install.stdout_lines

##Configuration file Template
- name: Netdata AWG Configurations
  template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
  notify:
      - Restart netdata

####Enable Notifications####
- lineinfile:
    dest: /etc/netdata/health_alarm_notify.conf
    regexp: '^DEFAULT_RECIPIENT_EMAIL="root"'
    line: 'DEFAULT_RECIPIENT_EMAIL="roderick.rabelo@awginc.com|critical"'
    backrefs: yes

####Disable network drop packages notifications####
- name: stat net.conf
  stat: path=/etc/netdata/health.d/net.conf
  register: netconf

- name: Disable Network notifications
    command: mv /etc/netdata/health.d/net.conf /etc/netdata/health.d/net.conf.DISABLED
    when: netconf.stat.exists

# we keep the sources for upgrades
#- name: "Clean git repo"
#  file:
#    path: /usr/src/netdata
#    state: absent

#Optional: Disable notifications
#- lineinfile:
#    dest: /etc/netdata/health_alarm_notify.conf
#    regexp: '^SEND_EMAIL="YES"'
#    line: 'SEND_EMAIL="NO"'
#    backrefs: yes


#ToDo Uninstaller -  see netdata-uninstaller.sh
