---
###Role: Packages Standards. RPM packages that are required on every server
###Owned by: Server Team, AWG
###Maintained by Roderick Rabelo (roderick.rabelo@awginc.com)
##
#
####INSTALLATION OF STANDARD PACKAGES####
- name: Install Standard packages
  yum: state=present name={{ item }}
  with_items:
    - nfs-utils
    - setroubleshoot-server
    - vim
    - ntp
    - logwatch
    - tzdata
    - cifs-utils
    - katello-agent
    #- htop
    - nmon
    - cockpit
#    - nmap

# - name: Install Katello Agent
#   yum:
#     name: katello-agent
#     state: present

#- name: Install htop
#  yum:
#    name: htop
#    state: present

####Install,starts and enable Cockpit for System Administration WebUI (https://hostname:9090)
#- name: Install Cockpit
#  yum:
#    name: cockpit
#    state: present

#- name: Start and Enable Cockpit
#  service: name=cockpit.socket state=started enabled=yes
