---
galaxy_info:
  author: Aleksandr Kostyrev
  description: Installs and configures foreman
  issue_tracker_url: https://github.com/kostyrevaa/ansible-role-foreman/issues
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
      - 7
      - 6
  categories:
    - cloud
    - system
dependencies: []
