---
ais_nonprod: /nonprod/ais_servers
ais_prod: /prod/ais_servers
batch_nonprod: /nonprod/batch_servers
batch_prod: /prod/batch_servers
rpe_nonprod: /nonprod/rpe_servers
rpe_prod: /prod/rpe_servers
was_prod: /prod/was_servers
infra_nonprod: /nonprod/infra_servers
infra_prod: /prod/infra_servers
