---
###Role:Satellite Subscription
###Owned by: Server Team, AWG
###Maintained by Roderick Rabelo (roderick.rabelo@awginc.com)
##
#
####Install Satellite CA Certificate####
- name: Install Satellite CA Certificate
  yum:
    name: http://satellite.awg.local/pub/katello-ca-consumer-latest.noarch.rpm
    state: present
  
####Subscribe to Satellite for Content####
- name: Subscribe to Satellite for Content
  redhat_subscription:
    state: present
    server_hostname: satellite.awg.local
    activationkey: AWG
    org_id: AWG