---

- name: Update SNMP configuration
  template:
    src: snmpd.conf.j2
    dest: '/etc/snmp/snmpd.conf'
    mode: 0640
    backup: yes
  notify:
    - restart_snmpd

- name: ensure service is enabled and started
  service: name=snmpd state=started enabled=yes