---

## yum_repository available in Ansible v2.0.x or earlier
##
#- name: Add InfluxData yum repository file
#  yum_repository:
#    name: influxdata
#    description: InfluxData repository
#    baseurl: "{{ influxdb_yum_repo_baseurl }}"
#    gpgkey: "{{ influxdb_signing_key_url }}"
#    gpgcheck: yes
#    enabled:  yes
#  when: influxdb_install_from_pkg_repo

- name: Add influxData yum repository
  template:
    src:   influxdata.yum.repo.j2
    dest:  /etc/yum.repos.d/influxdata.repo
    owner: root
    group: root
    mode:  0644

- name: Install influxdb
  yum:
    name:  "influxdb-{{ influxdb_version|default('*') }}"
    state: present
