---

##Installs SNMP Packages
- name: snmpd package install
  package: name=net-snmp state=present

##Installs SNMP-UTILS packages (snmpwalk,etc...)
- name: snmp-utils install
  package: name=net-snmp-utils

- include: snmpd.yml